schema_version: 1

context:
  version: "3.3.0"

package:
  name: throttled-py
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/throttled-py/throttled_py-${{ version }}.tar.gz
  sha256: f618fb1810de67240e608fc21dfd6e82dc68d96512bf33aedec117d89573f1e4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - throttled
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: High-performance Python rate limiting library with multiple algorithms (Fixed Window, Sliding Window, Token Bucket, Leaky Bucket & GCRA) and storage backends (Redis, In-Memory).
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ZhuoZhuoCrayon/throttled-py
  documentation: https://throttled-py.readthedocs.io

extra:
  recipe-maintainers:
    - thewchan
